### PR TITLE
Add blog post: C++ Tracker 0.1.0

### PR DESCRIPTION
**Pull request by ninjabear**
/cc @jbeemster

### CODE REVIEW

**Comment by alexanderdean** [comment]
@jbeemster can you do a first pass on this and then re-assign to me? Thanks!

**Comment by jbeemster** [comment]
@alexanderdean have had a pass through!  Actual repo has been squashed down to one commit as well, tests are all passing again, example is working - all green!

**Comment by alexanderdean** [comment]
Greenlight from me - please do the release!

**Comment by jbeemster** [comment]
@alexanderdean okay shall tag the repo now then!  Then I can merge this PR?

**Comment by alexanderdean** [comment]
Go for it!

**Pull request merged**
