### PR TITLE
Posts/r65 scarlet rosefinch

### PR DESCRIPTION
**Pull request by fblundun**

### CODE REVIEW

**Comment by alexanderdean** [comment]
Fred this looks great. I've made some minor tweaks. One more thing for tomorrow - in the Other changes section, could you add (#xx) links at the end of each bullet point. Many thanks!

**Comment by fblundun** [comment]
Good point! I'll add those in.

**Comment by fblundun** [comment]
Links have been added!

**Comment by alexanderdean** [comment]
Thanks Fred!

**Pull request merged**
