### PR TITLE
Schema Guru 0.4.0 release

### PR DESCRIPTION
**Pull request by chuwy**

### CODE REVIEW

**Comment by alexanderdean** [comment]
@chuwy - on Friday can you fill out the missing `issue-xx`s in the blog post that I added in?

**Comment by chuwy** [comment]
Sure!

**Comment by chuwy** [comment]
Done. Didn't filled [this one](https://github.com/snowplow/snowplow.github.com/pull/239/files#diff-5fe370083b264334ec4df8e42d34c2cbR138) because there's no such issue and it seems impossible for me.

**Comment by alexanderdean** [comment]
That's fine, thanks @chuwy

**Pull request merged**
